"""initial schema"""
from alembic import op
import sqlalchemy as sa
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer,primary_key=True),sa.Column('tg_id',sa.BigInteger,nullable=False),sa.Column('username',sa.String(64)),sa.Column('name',sa.String(80),nullable=False),sa.Column('age',sa.Integer),sa.Column('gender',sa.String(20)),sa.Column('looking_for',sa.String(20)),sa.Column('city',sa.String(100)),sa.Column('latitude',sa.Float),sa.Column('longitude',sa.Float),sa.Column('bio',sa.Text),sa.Column('moderation_status',sa.String(20),nullable=False),sa.Column('is_active',sa.Boolean,nullable=False),sa.Column('is_banned',sa.Boolean,nullable=False),sa.Column('deleted_at',sa.DateTime),sa.Column('vip_until',sa.DateTime),sa.Column('created_at',sa.DateTime,nullable=False),sa.Column('updated_at',sa.DateTime,nullable=False)); op.create_index('ix_users_tg_id','users',['tg_id'],unique=True); op.create_index('ix_users_moderation_status','users',['moderation_status']); op.create_index('ix_users_is_active','users',['is_active']); op.create_index('ix_users_is_banned','users',['is_banned']); op.create_index('ix_users_vip_until','users',['vip_until'])
    op.create_table('photos',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('file_id',sa.String(255),nullable=False),sa.Column('position',sa.Integer,nullable=False),sa.Column('moderation_status',sa.String(20),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False)); op.create_index('ix_photos_user_id','photos',['user_id']); op.create_index('ix_photos_moderation_status','photos',['moderation_status'])
    op.create_table('reactions',sa.Column('id',sa.Integer,primary_key=True),sa.Column('from_user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('to_user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('kind',sa.String(10),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False),sa.UniqueConstraint('from_user_id','to_user_id')); op.create_index('ix_reaction_from_date','reactions',['from_user_id','created_at'])
    op.create_table('matches',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_a_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('user_b_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False),sa.UniqueConstraint('user_a_id','user_b_id'))
    op.create_table('blocks',sa.Column('id',sa.Integer,primary_key=True),sa.Column('blocker_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('blocked_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False),sa.UniqueConstraint('blocker_id','blocked_id'))
    op.create_table('reports',sa.Column('id',sa.Integer,primary_key=True),sa.Column('reporter_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('reported_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('reason',sa.String(500),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False)); op.create_index('ix_reports_status','reports',['status'])
    op.create_table('payments',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('product',sa.String(50),nullable=False),sa.Column('stars',sa.Integer,nullable=False),sa.Column('payload',sa.String(255),nullable=False),sa.Column('telegram_charge_id',sa.String(255),nullable=False,unique=True),sa.Column('created_at',sa.DateTime,nullable=False)); op.create_index('ix_payments_user_id','payments',['user_id']); op.create_index('ix_payments_telegram_charge_id','payments',['telegram_charge_id'])
    op.create_table('audit_logs',sa.Column('id',sa.Integer,primary_key=True),sa.Column('admin_tg_id',sa.BigInteger,nullable=False),sa.Column('action',sa.String(100),nullable=False),sa.Column('target_id',sa.Integer),sa.Column('details',sa.Text),sa.Column('created_at',sa.DateTime,nullable=False)); op.create_index('ix_audit_logs_admin_tg_id','audit_logs',['admin_tg_id'])
def downgrade(): op.drop_table('audit_logs');op.drop_table('payments');op.drop_table('reports');op.drop_table('blocks');op.drop_table('matches');op.drop_table('reactions');op.drop_table('photos');op.drop_table('users')
